### ISSUE TITLE
Option "multipage = false" is not working properly

### ISSUE THREAD

**Issue by techmagus** [apvarun/showcase-hugo-theme#15]
Hi,

When the option "multipage" is set to "false", the menu filter is not working. If a menu is clicked it just changes the URL to /# In the old version of the theme, the /# is not added and filter works.

I tested it with the "exampleSite" folder as well, the result is the same.

Theme version -- not sure but my latest pull was 2021-07-06 (my last pull before today was sometime 2021 April or May).
Hugo version -- v0.85.0-extended.

Thank you.

**Comment by apvarun** [comment]
@techmagus Can you recheck the setup with the latest version? The issue has been addressed

**Comment by techmagus** [comment]
> @techmagus Can you recheck the setup with the latest version? The issue has been addressed

Hi,

Apologies for the late reply. It is working good now.

Thank you very much!

Shalom!
