### ISSUE TITLE
Going to "About" breaks filter links

### ISSUE THREAD

**Issue by trwnh** [apvarun/showcase-hugo-theme#5]
### Steps to reproduce
1. Click About
2. Click any of the filter links

### Expected behaviour
Going back to the home page and loading the appropriate filter

### Actual behaviour
Nothing happens

**Comment by apvarun** [comment]
@trwnh With the last change, the header was updated such that the filter links are only displayed in homepage.
Do you think that works for your usecase?

**Comment by trwnh** [comment]
I suppose it does, although more optimally the filters links would be separate from the nav links for UX reasons imo
