### ISSUE TITLE
Possible to remove the 's'

### ISSUE THREAD

**Issue by BurgerhoutJ** [apvarun/showcase-hugo-theme#7]
Is it possible to remove the 's' in the Automenu function? 
So that the theme does not generate from security to securities.

**Comment by apvarun** [comment]
@BurgerhoutJ There is no pluralisation function in the theme. The header item will be same as the name of the folder your data is in.

**Comment by BurgerhoutJ** [comment]
@apvarun, that's not really true. See the provided screenshots. Compare the folder names and the header.
![content folders](https://user-images.githubusercontent.com/25769575/100252137-d8b33380-2f3f-11eb-8a71-24ae610bf816.png)
![header](https://user-images.githubusercontent.com/25769575/100252141-d94bca00-2f3f-11eb-828d-bfa105de276b.png)

**Comment by BurgerhoutJ** [comment]
Found it. Put `pluralizelisttitles = false` in the config.toml file. 
![image](https://user-images.githubusercontent.com/25769575/100252639-5f681080-2f40-11eb-96ff-2fe38dcad13b.png)

**Comment by apvarun** [comment]
Apparently that's a Hugo thing. Thanks for letting me know :)
